[package]
name = "yggtrackerd"
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"
description = "BitTorrent aggregation web-server, based on the Rocket framework and aquatic-crawler FS"
keywords = ["yggtracker", "bittorrent", "server", "aggregator", "catalog"]
categories = ["network-programming"]
repository = "https://github.com/YGGverse/yggtrackerd"
# homepage = "https://yggverse.github.io"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rocket = "0.5"
librqbit-core = "5.0"
chrono = { version = "0.4.41", features = ["serde"] }
url = { version = "2.5", features = ["serde"] }
urlencoding = "2.1"
rocket_dyn_templates = { version = "0.2", features = ["tera"] }
